#ifndef QTMETAOBJECTFRAMEWORK_GLOBAL_H
#define QTMETAOBJECTFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMETAOBJECTFRAMEWORK_LIBRARY)
#  define QTMETAOBJECTFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMETAOBJECTFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMETAOBJECTFRAMEWORK_GLOBAL_H
